

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#  redis:
#    database: 0 #Redis数据库索引，默认0
#    host: 127.0.0.1 #IP
#    port: 6379 #端口
#    password: #密码
#    connect-timeout: 5000 #连接超时时间（毫秒）

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    org.com.cn.project.*.controller: DEBUG
  file:
    path: F:\\manage\\1_work\\springboot-demo.log
  logback:
    rollingpolicy:
      max-file-size: 10
server:
  port: 9082

template:
  templatePath: /template/
  templateFileName: template.xlsx